const fs = require('fs');
const path = require('path');
const Url = require('url-parse');


let readStream = fs.createReadStream(path.resolve(__dirname, './list_of_uri_endpoints.txt')),
    remaining = '',
    _json = {data:[]};

readStream.on('data', (data) => {
    remaining += data;
    let index = remaining.indexOf('\n');
    while(index > -1) {
        let line = remaining.substring(0, index);
        remaining = remaining.substr(index + 1);
        createJson(line);
        index = remaining.indexOf('\n');
    }
});

readStream.on('end', () => {
    if(remaining.length > 0){
        createJson(remaining);
    }
    writeToFile(_json)
});

function createJson(line){
    let url = new Url(line);
    _json.data.push({uri: line, host: url.host, options: url.pathname + url.query})
}

function writeToFile(data){
    const file = path.resolve(__dirname, '../mappers/dist/uri_json.json');
    fs.writeFile(file, '/** This file is auto generated by build_uri_endpoint_mapper.js under the scripts folder **/ \n', (error) => {
        if(error) {
            console.log('----- could not save file --- : scripts/build_uri_endpoint');
            return;
        }

        fs.appendFile(file, JSON.stringify(data, null, 4));

        console.log('------- SAVED - uri endpoint JSON');
    });
}



