version: '3'
services:
  news:
    build: ./news
    ports:
      - "3003:3003"
    expose:
      - "3003"
  sports:
    build: ./sports
    ports:
      - "3002:3002"
    expose:
      - "3002"
  web:
    build: ./src
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - news
      - sports
    depends_on:
      - news
      - sports