apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: testharness
  labels:
    run: expressproxy-svc
  name: expressproxy-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      run: expressproxy-svc
  template:
    metadata:
      labels:
        run: expressproxy-svc
    spec:
      containers:
      - name: expressproxy-svc
        image: 460570964411.dkr.ecr.us-west-2.amazonaws.com/charter/raven/testharness:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      - name: expressproxy-ui
        image: 460570964411.dkr.ecr.us-west-2.amazonaws.com/charter/raven/testharness:UIv1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: testharness
  name: expressproxy-svc
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: expressproxy-svc
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  namespace: testharness
  name: expressproxy-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    name: web
    protocol: TCP
    targetPort: 3000
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: api
  selector:
    run: expressproxy-svc